### ISSUE TITLE
Reloading services

### ISSUE THREAD

**Issue by martyphee** [jhipster/jhipster-loaded#8] opened 2014-05-29 14:22 UTC
Was 0.7 release supposed to fix this or is it a issue with spring?

I'm still getting the same warnings after upgrading to 0.7.

The bean is defined as such

``` java
@Service("STUDENT_POLL_SERVICE")
public class StudentPollService extends AbstractInteractionManager<StudentPoll,StudentPoll.StudentPollChoice> {
```

```
[INFO] io.github.jhipster.loaded.JHipsterReloaderThread - Batch reload in progress...
[WARN] io.github.jhipster.loaded.reloader.SpringReloader - Could not hot reload Spring bean!
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.ceshop.controlcenter.service.lesson.StudentPollService] is defined
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:319) ~[spring-beans-4.0.3.RELEASE.jar:4.0.3.RELEASE]
    at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:985) ~[spring-context-4.0.3.RELEASE.jar:4.0.3.RELEASE]
    at io.github.jhipster.loaded.reloader.SpringReloader.start(SpringReloader.java:162) [core-0.7.jar:na]
    at io.github.jhipster.loaded.reloader.SpringReloader.reload(SpringReloader.java:106) [core-0.7.jar:na]
    at io.github.jhipster.loaded.JHipsterReloaderThread.batchReload(JHipsterReloaderThread.java:206) [core-0.7.jar:na]
    at io.github.jhipster.loaded.JHipsterReloaderThread.run(JHipsterReloaderThread.java:153) [core-0.7.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_05]
```

**Comment by jmirc** [comment] 2014-07-10 12:18
I am closing because I am not able to reproduce the bug with the version 0.8

**Closed as completed by jmirc** 2014-07-10 12:18 UTC
